### ISSUE TITLE
Roadmap and contribution guidelines

### ISSUE THREAD

**Issue by fabiomontefuscolo** [terzinnorbert/syncthing-rest#1]
Hi!

This is indeed a very interesting project to launch! I was thinking to start something to work with syncthing, but boss where I work pointed me your repository. We would like to contribute. Well, I can contribute with code and documentation, that is all I have for now. :grimacing: But soon I would like to pay you a beer or a coffee.

Could you point us how to contribute?

Thank you very much!

**Comment by terzinnorbert** [comment]
Hi,

Sorry for the late reply. I have no bigger plan for this repository. I mean, this state is more than enough for my other project, so if you have any idea feel free to implement :)
